{
https://cgstranchi.gov.in/dhnbad_area.php 
https://www.gsi.gov.in/webcenter/portal/OCBIS/pagesouthern 
https://iscs-eresource.gov.in/web
https://www.gsi.gov.in/webcenter/portal/OCBIS/pagewestern
https://eci.gov.in/
https://www.gsi.gov.in/webcenter/portal/OCBIS/pagenortheastern
https://www.gsi.gov.in/webcenter/portal/OCBIS/pagenorthern
https://ibm.gov.in/index.php?c=pages&m=index&id=219
https://ibm.gov.in/index.php?c=pages&m=index&id=221
https://www.gsi.gov.in/webcenter/portal/OCBIS/pagecentral
https://ibm.gov.in/index.php?c=pages&m=index&id=217
https://www.mod.gov.in/dod
https://ncdc.gov.in/index1.php?lang=1&level=1&sublinkid=703&lid=550
https://gstdelhizone.gov.in/south/index-south.php
https://www.gsi.gov.in/webcenter/portal/OCBIS/pageeastern
https://nhrc.nic.in/
https://mausam.imd.gov.in/ahmedabad
https://mausam.imd.gov.in/kolkata
https://mausam.imd.gov.in/bengaluru
https://ibm.gov.in/index.php?c=pages&m=index&id=223
https://www.psa.gov.in/
https://niti.gov.in/
https://ibm.gov.in/index.php?c=pages&m=index&id=214
https://mausam.imd.gov.in/agartala
https://ibm.gov.in/index.php?c=pages&m=index&id=218
https://ibm.gov.in/index.php?c=pages&m=index&id=216
https://ibm.gov.in/index.php?c=pages&m=index&id=222
https://cag.gov.in/
https://ibm.gov.in/index.php?c=pages&m=index&id=220
https://mausam.imd.gov.in/dehradun
https://ibm.gov.in/index.php?c=pages&m=index&id=224
https://ddpdoo.gov.in/units/NADP
https://ceeindia.org/envis
}